-- 4-Pillar recipe columns for deck creation
ALTER TABLE decks ADD COLUMN IF NOT EXISTS maturity TEXT DEFAULT 'adult';
ALTER TABLE decks ADD COLUMN IF NOT EXISTS flavor_themes JSONB DEFAULT '[]';
ALTER TABLE decks ADD COLUMN IF NOT EXISTS chaos_level INTEGER DEFAULT 0;
ALTER TABLE decks ADD COLUMN IF NOT EXISTS wildcard TEXT DEFAULT '';
ALTER TABLE decks ADD COLUMN IF NOT EXISTS remixed_from TEXT REFERENCES decks(id);
ALTER TABLE decks ADD COLUMN IF NOT EXISTS game_type TEXT DEFAULT 'cah';
ALTER TABLE decks ADD COLUMN IF NOT EXISTS art_tier TEXT DEFAULT 'free';
ALTER TABLE decks ADD COLUMN IF NOT EXISTS art_generation_status TEXT DEFAULT NULL;
ALTER TABLE decks ADD COLUMN IF NOT EXISTS draft BOOLEAN DEFAULT FALSE;
